# Generated by Django 3.1 on 2021-05-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0003_auto_20210514_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='E.g. BitCoin, Rupee, Dollar etc.', max_length=50)),
                ('description', models.TextField(help_text='Few words about the currency.')),
                ('effective_place', models.ManyToManyField(to='place.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='E.g. Vibranium, Pym Particles, Energons etc.', max_length=50)),
                ('description', models.TextField(help_text='Few words about the resource.')),
                ('value', models.PositiveIntegerField(help_text='Numerical value of the currency in which 1 Unit of resource can be traded.')),
                ('accepted_currency', models.ForeignKey(help_text='Name of the currency in which resource can be traded.', on_delete=django.db.models.deletion.CASCADE, related_name='tradable_resources', to='resources.currency')),
                ('origin', models.ForeignKey(help_text='Place where the resource can be found!', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='place.place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
