# Generated by Django 3.1 on 2021-05-13 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0004_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='E.g. Earth, Dimension 616, Delhi etc.', max_length=200)),
                ('description', models.TextField(help_text='Some description of the place.')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_within', to='place.place')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='timeline.timeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(help_text='E.g. First World War, Battle of Bastards etc.', max_length=500)),
                ('description', models.TextField(help_text='Details of the event.')),
                ('time_started', models.CharField(help_text='E.g. 1914, 320 BC etc.', max_length=20)),
                ('time_ended', models.CharField(help_text='E.g. 1918, Present etc.', max_length=20)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='place.place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
