# Generated by Django 3.1 on 2021-05-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20210514_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places_within', to='place.place'),
        ),
    ]
