# Generated by Django 3.1 on 2021-05-12 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('era', models.CharField(help_text='E.g. Jurrassic, Stone Age, Satayuga etc.', max_length=200)),
                ('start_period', models.BigIntegerField(help_text='E.g. 1914, 2000, 420 etc.', max_length=10)),
                ('end_period', models.BigIntegerField(help_text='E.g. 1914, 2000, 420 etc.', max_length=10)),
                ('label', models.CharField(help_text='E.g. BC, AD, BCE etc.', max_length=4)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
