# Generated by Django 3.1 on 2021-05-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20210513_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(help_text='E.g. First World War, Battle of Bastards etc.', max_length=500)),
                ('description', models.TextField(help_text='Details of the event.')),
                ('time_started', models.CharField(help_text='E.g. 1914, 320 BC etc.', max_length=20)),
                ('time_ended', models.CharField(help_text='E.g. 1918, Present etc.', max_length=20)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timeline.timeline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
