# Generated by Django 3.1 on 2021-05-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0003_auto_20210514_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='E.g. Avengers, Starfleet, Jedi Order etc.', max_length=100)),
                ('description', models.TextField(help_text='Some words about the faction.')),
                ('objective', models.CharField(help_text='E.g. Protecting Earth, Maintaining Peace etc.', max_length=500)),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factions_associated', to='place.place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
