# Generated by Django 3.1 on 2021-05-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0003_auto_20210514_0341'),
        ('faction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(help_text='E.g. Harry, Jon, Steve etc.', max_length=50)),
                ('lastname', models.CharField(help_text='E.g. Potter, Snow, Rogers etc.', max_length=50)),
                ('aliases', models.CharField(blank=True, help_text='You can add more than one using comma(,)', max_length=200, null=True)),
                ('age', models.PositiveIntegerField(help_text='Age in years')),
                ('appearance', models.TextField(help_text='Details about physical appearance.')),
                ('behaviour', models.TextField(help_text='Details about mental behaviour.')),
                ('events', models.ManyToManyField(related_name='characters_associated', to='place.Event')),
                ('factions', models.ManyToManyField(related_name='members', to='faction.Faction')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_associated', to='place.place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
